"""Trạng thái Group Discovery, Join và Link Share. Không vượt CAPTCHA hay checkpoint."""

from __future__ import annotations

MEMBERSHIP_NOT_JOINED = "NOT_JOINED"
MEMBERSHIP_JOINED = "JOINED"
MEMBERSHIP_PENDING = "PENDING"
MEMBERSHIP_APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
MEMBERSHIP_UNKNOWN = "UNKNOWN"

APPROVAL_NONE = "NO_APPROVAL_INDICATED"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
APPROVAL_UNKNOWN = "UNKNOWN"

POSTING_ALLOWED = "ALLOWED"
POSTING_DENIED = "DENIED"
POSTING_UNKNOWN = "UNKNOWN"

DISCOVERY_PENDING = "PENDING"
DISCOVERY_RUNNING = "RUNNING"
DISCOVERY_COLLECTING = "COLLECTING"
DISCOVERY_FILTERING = "FILTERING"
DISCOVERY_DEDUPLICATING = "DEDUPLICATING"
DISCOVERY_SAVING = "SAVING"
DISCOVERY_COMPLETED = "COMPLETED"
DISCOVERY_PAUSED = "PAUSED"
DISCOVERY_RATE_LIMITED = "RATE_LIMITED"
DISCOVERY_FAILED = "FAILED"
DISCOVERY_CANCELLED = "CANCELLED"

JOIN_PENDING = "PENDING"
JOIN_VALIDATING = "VALIDATING"
JOIN_CHECKING_SESSION = "CHECKING_SESSION"
JOIN_OPENING_GROUP = "OPENING_GROUP"
JOIN_CHECKING_STATUS = "CHECKING_JOIN_STATUS"
JOIN_JOINING = "JOINING"
JOIN_VERIFYING = "VERIFYING_MEMBERSHIP"
JOIN_JOINED = "JOINED"
JOIN_ALREADY = "ALREADY_JOINED"
JOIN_APPROVAL = "APPROVAL_REQUIRED"
JOIN_NOT_AVAILABLE = "NOT_AVAILABLE"
JOIN_FAILED = "FAILED"
JOIN_PAUSED = "PAUSED"
JOIN_WAITING_REAUTH = "WAITING_REAUTH"
JOIN_CANCELLED = "CANCELLED"
JOIN_DELAYED = "DELAYED"

SHARE_PENDING = "PENDING"
SHARE_VALIDATING = "VALIDATING"
SHARE_CHECKING_SESSION = "CHECKING_SESSION"
SHARE_CHECKING_PERMISSION = "CHECKING_PERMISSION"
SHARE_READY = "READY"
SHARE_OPENING_GROUP = "OPENING_GROUP"
SHARE_CREATE_POST = "CREATE_POST"
SHARE_INSERT_TEXT = "INSERT_TEXT"
SHARE_INSERT_URL = "INSERT_SOURCE_URL"
SHARE_WAIT_PREVIEW = "WAIT_LINK_PREVIEW"
SHARE_SUBMIT = "SUBMIT"
SHARE_VERIFYING = "VERIFYING"
SHARE_VERIFY_FIRST = "VERIFY_FIRST"
SHARE_COMPLETED = "COMPLETED"
SHARE_DUPLICATE = "DUPLICATE"
SHARE_SKIPPED = "SKIPPED"
SHARE_FAILED = "FAILED"
SHARE_PAUSED = "PAUSED"
SHARE_WAITING_REAUTH = "WAITING_REAUTH"
SHARE_CANCELLED = "CANCELLED"

BATCH_CREATED = "CREATED"
BATCH_VALIDATING = "VALIDATING"
BATCH_READY = "READY"
BATCH_RUNNING = "RUNNING"
BATCH_DELAYING = "DELAYING"
BATCH_COMPLETED = "COMPLETED"
BATCH_PAUSED = "PAUSED"
BATCH_FAILED = "FAILED"
BATCH_CANCELLED = "CANCELLED"

SOURCE_POST = "FACEBOOK_POST_URL"
SOURCE_VIDEO = "FACEBOOK_VIDEO_URL"
SOURCE_PUBLIC = "SUPPORTED_PUBLIC_URL"

ERR_SESSION = "SESSION_EXPIRED"
ERR_PERMISSION = "PERMISSION_DENIED"
ERR_NOT_JOINED = "GROUP_NOT_JOINED"
ERR_POSTING = "POSTING_NOT_ALLOWED"
ERR_NETWORK = "NETWORK_ERROR"
ERR_TIMEOUT = "TIMEOUT"
ERR_CAPTCHA = "CAPTCHA"
ERR_CHECKPOINT = "CHECKPOINT"
ERR_SECURITY = "SECURITY_VERIFICATION"
ERR_RATE = "RATE_LIMITED"
ERR_TEMPORARY = "TEMPORARY_ERROR"

MAX_RETRY = 3
MAX_ACTIVE_JOIN = 1
MAX_ACTIVE_PUBLISH = 1

TEMPORARY_ERROR_CODES = frozenset({ERR_NETWORK, ERR_TIMEOUT, ERR_TEMPORARY})
PAUSE_CODES = frozenset({ERR_CAPTCHA, ERR_CHECKPOINT, ERR_SECURITY, ERR_RATE, ERR_SESSION})
SKIP_CODES = frozenset({ERR_PERMISSION, ERR_NOT_JOINED, ERR_POSTING})

JOIN_DONE = frozenset({JOIN_JOINED, JOIN_ALREADY, JOIN_APPROVAL, JOIN_NOT_AVAILABLE, JOIN_FAILED, JOIN_CANCELLED})
SHARE_DONE = frozenset({SHARE_COMPLETED, SHARE_DUPLICATE, SHARE_SKIPPED, SHARE_FAILED, SHARE_CANCELLED})
DISCOVERY_ACTIVE = frozenset(
    {
        DISCOVERY_RUNNING,
        DISCOVERY_COLLECTING,
        DISCOVERY_FILTERING,
        DISCOVERY_DEDUPLICATING,
        DISCOVERY_SAVING,
    }
)
JOIN_ACTIVE = frozenset(
    {
        JOIN_VALIDATING,
        JOIN_CHECKING_SESSION,
        JOIN_OPENING_GROUP,
        JOIN_CHECKING_STATUS,
        JOIN_JOINING,
        JOIN_VERIFYING,
    }
)
SHARE_ACTIVE = frozenset(
    {
        SHARE_VALIDATING,
        SHARE_CHECKING_SESSION,
        SHARE_CHECKING_PERMISSION,
        SHARE_READY,
        SHARE_OPENING_GROUP,
        SHARE_CREATE_POST,
        SHARE_INSERT_TEXT,
        SHARE_INSERT_URL,
        SHARE_WAIT_PREVIEW,
        SHARE_SUBMIT,
        SHARE_VERIFYING,
        SHARE_VERIFY_FIRST,
    }
)
