"""Trạng thái batch / job tạo Facebook Page."""

from __future__ import annotations

BATCH_CREATED = "CREATED"
BATCH_VALIDATING = "VALIDATING"
BATCH_READY = "READY"
BATCH_RUNNING = "RUNNING"
BATCH_PAUSED = "PAUSED"
BATCH_PAUSED_FOR_USER = "PAUSED_FOR_USER"
BATCH_DELAYING = "DELAYING"
BATCH_COMPLETED = "COMPLETED"
BATCH_FAILED = "FAILED"
BATCH_CANCELLED = "CANCELLED"

JOB_PENDING = "PENDING"
JOB_VALIDATING = "VALIDATING"
JOB_CHECKING_SESSION = "CHECKING_SESSION"
JOB_CREATING = "CREATING"
JOB_UPLOADING_AVATAR = "UPLOADING_AVATAR"
JOB_FILLING_DETAILS = "FILLING_DETAILS"
JOB_ADDING_ADMIN = "ADDING_ADMIN"
JOB_VERIFYING = "VERIFYING"
JOB_RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
JOB_COMPLETED = "COMPLETED"
JOB_WAITING_REAUTH = "WAITING_REAUTH"
JOB_CHECKPOINT = "CHECKPOINT"
JOB_CAPTCHA_DETECTED = "CAPTCHA_DETECTED"
JOB_RATE_LIMITED = "RATE_LIMITED"
JOB_SMS_VERIFICATION_REQUIRED = "SMS_VERIFICATION_REQUIRED"
JOB_ACCOUNT_SECURITY_CHECK = "ACCOUNT_SECURITY_CHECK"
JOB_BLOCKED_BY_ACCOUNT_VERIFICATION = "BLOCKED_BY_ACCOUNT_VERIFICATION"
JOB_READY_TO_RESUME = "READY_TO_RESUME"
JOB_PAUSED_FOR_USER = "PAUSED_FOR_USER"
JOB_FAILED = "FAILED"
JOB_CANCELLED = "CANCELLED"
JOB_DELAYED = "DELAYED"

ACCOUNT_LOCK_SECURITY_VERIFICATION_REQUIRED = "SECURITY_VERIFICATION_REQUIRED"
ACCOUNT_LOCK_READY = "READY"

TEMPORARY_ERROR_CODES = frozenset(
    {"NETWORK_TIMEOUT", "TEMPORARY_ERROR", "NAVIGATION_TIMEOUT"}
)
USER_ACTION_CODES = frozenset(
    {
        "SESSION_EXPIRED",
        "CAPTCHA_DETECTED",
        "CHECKPOINT",
        "RATE_LIMITED",
        "SMS_VERIFICATION_REQUIRED",
        "SECURITY_VERIFICATION_REQUIRED",
        "ACCOUNT_SECURITY_CHECK",
    }
)
SECURITY_PAUSE_CODES = frozenset(
    {
        "SMS_VERIFICATION_REQUIRED",
        "SECURITY_VERIFICATION_REQUIRED",
        "CAPTCHA_DETECTED",
        "CHECKPOINT",
        "SESSION_EXPIRED",
        "RATE_LIMITED",
    }
)

INCOMPLETE_BATCH_STATUSES = frozenset(
    {
        BATCH_RUNNING,
        BATCH_DELAYING,
        BATCH_PAUSED,
        BATCH_PAUSED_FOR_USER,
        BATCH_READY,
        "CREATING",
    }
)
RECOVERY_JOB_STATUSES = frozenset(
    {
        JOB_CREATING,
        JOB_VERIFYING,
        JOB_UPLOADING_AVATAR,
        JOB_FILLING_DETAILS,
        JOB_ADDING_ADMIN,
        JOB_RECOVERY_REQUIRED,
        JOB_CHECKING_SESSION,
        JOB_ACCOUNT_SECURITY_CHECK,
    }
)
USER_HELD_JOB_STATUSES = frozenset(
    {
        JOB_WAITING_REAUTH,
        JOB_CHECKPOINT,
        JOB_CAPTCHA_DETECTED,
        JOB_RATE_LIMITED,
        JOB_SMS_VERIFICATION_REQUIRED,
        JOB_PAUSED_FOR_USER,
        JOB_ACCOUNT_SECURITY_CHECK,
        JOB_READY_TO_RESUME,
    }
)
